feat: 이메일 로그인 구현
Hwanvely/Gooroom_WebApplication pull request #6
Opened 2023-05-05 19:25 UTC by juns1s

네이버 로그인 api에 맞춘 변수명에 따라
변수명 변경 완료 했고 테스트도 나름 통과했습니다.

2023-05-05 19:48 UTC, Hwanvely commented on projectgooroom/src/main/java/GooRoom/projectgooroom/config/SecurityConfig.java
> +    private final JwtService jwtService;
이미 추가해 놨는데 빼주실수 있나요

2023-05-05 19:51 UTC, Hwanvely commented on projectgooroom/src/main/java/GooRoom/projectgooroom/config/SecurityConfig.java
> +                .requestMatchers("/users/**").permitAll() //회원가입 접근 가능
여기서 부터 return 전까지 토의 한번 해봐야겠네요

2023-05-05 19:53 UTC, Hwanvely commented on projectgooroom/src/main/java/GooRoom/projectgooroom/config/SecurityConfig.java
> +        provider.setUserDetailsService(emailMemberService);
이 부분 토의가 필요합니다

2023-05-05 20:01 UTC, Hwanvely requested changes
member filter랑 memberhandler 부분은 OAuth2와 겹쳐서 따로 정리 해야 할것 같습니다

2023-05-06 01:19 UTC, juns1s commented
합치는건 어떤가요

2023-05-06 02:00 UTC, closed without merging